# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

name: Dart

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: 2.x

      - name: Install dependencies
        run: flutter pub get

      - name: Build aab bundle 
        run: flutter build appbundle --release
        
      - name: Sign and upload to Google Play Store
        uses: r0adkll/upload-google-play@v1
        with:
          packageName: com.personal.movie_app
          releaseFiles: build/app/outputs/bundle/release/app-release.aab
          serviceAccountJsonPlainText: ${{ secrets.PLAYSTORE_ACCOUNT_KEY }}
          track: internal # Set the desired release track (e.g., internal, alpha, beta, production)
          releasename: MovieApp v1.1.0 # Set the release name
          release_notes: Initial release plus 1 # Set the release notes
        
      - name: Move aab file 
        run: mv build/app/outputs/bundle/release/app-release.aab mybuilds/

      - name: Archive artifacts
        uses: actions/upload-artifact@v2
        with:
          name: ABB
          path: mybuilds/app-release.aab
